#!/usr/bin/env sh
test "$1" == '' && (echo WARN please set keyword for process should be killed; exit 1)
pids_this_proc=$(ps aux | grep $0 | awk '{print $2}')
pids_other="$(ps aux | grep $1 2>/dev/null | grep -v "$pids_this_proc" 2>/dev/null | awk '{print $2}')"; kill $pids_other 2>/dev/null
